# Test against this version of Node.js
environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run mocha

# Don't actually build.
build: off
